### ISSUE TITLE
JavaScript error: Discontiguous selection is not supported.

### ISSUE THREAD

**Issue by Manc** [Waxolunist/bootstrap3-wysihtml5-bower#72]
Sorry for only providing fuzzy information...

Yesterday I included `bootstrap3-wysihtml5.all.min.js` in a page and I cannot remember having noticed any problems.

Today, after Google Chrome has updated to version 36.0.1985.125, I noticed an error and a warning in the JavaScript console, although I'm not absolutely sure if that's not been there already.

Firstly, the warning:
`'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).`

Secondly, the error:
`Discontiguous selection is not supported.`

If I get the time I'll try to narrow it down by not using the minified script. For now I just wanted to share that with you.

**Comment by timdown** [comment]
Someone had already taken the `rangy` Bower package name when I first put Rangy on Bower, so I used `rangy-official`. Since then, the `rangy` name has been transferred to me and `rangy` is now the official package.

The `rangy-release` repository is just for Bower and is always kept in sync with Rangy releases. It's inconvenient but seems to be the simplest way to publish to Bower without drastically changing the structure of the main Rangy repository.

**Comment by Waxolunist** [comment]
@timdown Thank you for sharing. I will correct it at https://github.com/bootstrap-wysiwyg/bootstrap3-wysiwyg
